spring:
  profiles:
    include:
      - mysql
      - s3

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800